# Only enable this site if you have a wildcard SSL cert!
server {
  listen 443;
  listen [::]:443;

  server_name _;
  root /var/www/default;

  ssl_certificate /etc/nginx/cert/<domain>/cert/fullchain.pem;
  ssl_certificate_key /etc/nginx/cert/<domain>/cert/key.pem;

  location ~ /\. {
    deny all;
  }

  location / {
    try_files $uri $uri/ $uri.html =404;
  }

   access_log off;
   error_log off;
}

