services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped

    extra_hosts:
      - "host.docker.internal:host-gateway"

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro,z
      - ./nginx/html:/var/www:ro,z
      - /srv/docker/letsencrypt/cert:/etc/nginx/cert:ro,z
