[Audio]
PreferredLanguage=jpn,jp,jap,Japanese,eng,en,enUS,en-US,English
Volume=100

[General]
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
HWDecoding=nvdec
YtdlFormat=bestvideo+bestaudio/best

[Playlist]
Autoplay=false
CanToggleWithMouse=false
OverlayVideo=false
ShowRowNumber=false
Style=compact

[Subtitles]
PreferredLanguage=eng,en,enUS,en-US,English,jpn,jp,jap,Japanese
SubtitlesFolders=subs,.

[Video]
ScreenshotFormat=png
