# See smb.conf.example for a more detailed config file or
# read the smb.conf manpage.
# Run 'testparm' to verify the config is correct after
# you modified it.
#
# Note:
# SMB1 is disabled by default. This means clients without support for SMB2 or
# SMB3 are no longer able to connect to smbd (by default).

# Note: Samba users must exist as Linux users _and_ samba users.
# By using "smbpasswd" and enabling "unix password sync" you can keep these in sync.
#
# Add a user
# smbpasswd -a "username"
#
# Enable it
# smbpasswd -e "username"
#
# If existing, change it
# smbpasswd asd
#
# You can also use my own utility "add-samba-user.sh <username>"


[global]
  workgroup = SAMBA
  security = user

  passdb backend = tdbsam

  # Updates the UNIX password to the same password set by samba
  unix password sync = yes
  passwd program = /usr/bin/passwd %u
  passwd chat = *New*password:* %n\n *Retype*new*password:* %n\n *updated*successfully*

  load printers = no
  # Install samba-usershares package for support
  include = /etc/samba/usershares.conf


[erik]
  path = /home/erik
  valid users = erik
  browseable = no
  read only = no
  writable = yes
  guest ok = no
  create mask = 0600
  directory mask = 0700

[mnt]
  path = /mnt
  valid users = erik
  browseable = no
  read only = no
  writable = yes
  guest ok = no
  create mask = 0775
  directory mask = 0775

