server {
  listen 80;
  listen [::]:80;
  listen 443 ssl;
  listen [::]:443 ssl;

  server_name git.kira.rip;
  root /var/www/empty;

  ssl_certificate /etc/nginx/cert/kira.rip/cert/fullchain.pem;
  ssl_certificate_key /etc/nginx/cert/kira.rip/cert/key.pem;

  location ~ /\. {
    deny all;
  }
  access_log off;
  error_log off;

  return 307 https://github.com/Kira9204;
}
